# Generated by Django 5.2.11 on 2026-02-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_notificationoutbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationoutbox',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
